[platformio]
description = Multi-Teensy System

[env:TeensyHVAC]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 4-20ma/ModbusMaster@^2.0.1
         = bblanchon/ArduinoJson@^7.4.1
build_flags = -D USB_TRIPLE_SERIAL
upload_command = tycmd upload -B $UPLOAD_PORT $SOURCE
upload_port = 13143020-Teensy ;This is the serial port name for Teensy 4.1
build_src_filter =
  +<*>
  -<TeensyLeft/>
  -<TeensyRight/>

[env:TeensyLeft]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 4-20ma/ModbusMaster@^2.0.1
build_flags = -D USB_TRIPLE_SERIAL
upload_command = tycmd upload -B $UPLOAD_PORT $SOURCE
upload_port = 13142960-Teensy ;This is the serial port name for Teensy 4.1
build_src_filter =
  +<*>
  -<TeensyHVAC/>
  -<TeensyRight/>

[env:TeensyRight]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 4-20ma/ModbusMaster@^2.0.1
build_flags = -D USB_TRIPLE_SERIAL
upload_command = tycmd upload -B $UPLOAD_PORT $SOURCE
upload_port = 13142880-Teensy ;This is the serial port name for Teensy 4.1
build_src_filter =
  +<*>
  -<TeensyHVAC/>
  -<TeensyLeft/>